// 지역 정보. 새 지역을 추가하려면 이 배열 끝에 항목을 하나 더 넣으면 된다.
export const regions = [
  {
    id: "forest",
    name: "초록 숲",
    element: "자연",
    monsters: [
      { name: "슬라임", emoji: "🟢" },
      { name: "고블린", emoji: "👺" },
      { name: "늑대", emoji: "🐺" },
      { name: "버섯괴물", emoji: "🍄" },
      { name: "멧돼지", emoji: "🐗" },
      { name: "다람쥐 전사", emoji: "🐿️" },
      { name: "나무 정령", emoji: "🌳" },
    ],
    boss: { name: "고블린 족장", emoji: "👹" },
    clearStory: "고블린 족장을 쓰러뜨리자, 숲 너머로 향하는 낡은 갱도 입구가 드러났다.",
  },
  {
    id: "mine",
    name: "버려진 광산",
    element: "어둠",
    monsters: [
      { name: "박쥐", emoji: "🦇" },
      { name: "스켈레톤", emoji: "💀" },
      { name: "두더지 광부", emoji: "⛏️" },
      { name: "동굴 거미", emoji: "🕷️" },
      { name: "좀비 광부", emoji: "🧟" },
      { name: "유령 광부", emoji: "👻" },
      { name: "그림자 쥐", emoji: "🐀" },
    ],
    boss: { name: "해골 광산왕", emoji: "☠️" },
    clearStory: "해골 광산왕이 무너지며, 안개 자욱한 늪으로 이어지는 길이 열렸다.",
  },
  {
    id: "swamp",
    name: "안개 늪지",
    element: "물",
    monsters: [
      { name: "도마뱀 전사", emoji: "🦎" },
      { name: "늪 마녀", emoji: "🧙‍♀️" },
      { name: "거대 개구리", emoji: "🐸" },
      { name: "악어", emoji: "🐊" },
      { name: "늪 지네", emoji: "🐛" },
      { name: "반딧불 요정", emoji: "✨" },
      { name: "진흙 골렘", emoji: "🟤" },
    ],
    boss: { name: "늪의 마녀 모르가", emoji: "🧙" },
    clearStory: "늪의 마녀 모르가를 물리쳤다. 다음 이야기는 계속됩니다...",
  },
  {
    id: "canyon",
    name: "불꽃 협곡",
    element: "불",
    monsters: [
      { name: "화염 정령", emoji: "🔥" },
      { name: "오우거", emoji: "👹" },
      { name: "용암 거북", emoji: "🐢" },
      { name: "마그마 웜", emoji: "🪱" },
      { name: "불꽃 임프", emoji: "😈" },
      { name: "화산개미", emoji: "🐜" },
      { name: "재의 정령", emoji: "💨" },
    ],
    boss: { name: "화산 거인", emoji: "🌋" },
    clearStory: "화산 거인이 무너지자 협곡의 열기가 가라앉고, 저 멀리 얼어붙은 성채가 보이기 시작했다.",
  },
  {
    id: "citadel",
    name: "얼음 성채",
    element: "물",
    monsters: [
      { name: "서리 기사", emoji: "🥶" },
      { name: "설인", emoji: "⛄" },
      { name: "아이스 골렘", emoji: "🧊" },
      { name: "펭귄 전사", emoji: "🐧" },
      { name: "눈보라 정령", emoji: "❄️" },
      { name: "빙하 거인", emoji: "🏔️" },
      { name: "서리 부엉이", emoji: "🦉" },
    ],
    boss: { name: "아이스 드래곤", emoji: "🐉" },
    clearStory: "아이스 드래곤을 쓰러뜨렸다. 성채 너머 하늘에 떠 있는 섬이 어렴풋이 보인다.",
  },
  {
    id: "sky",
    name: "하늘 섬",
    element: "빛",
    monsters: [
      { name: "그리폰", emoji: "🦅" },
      { name: "천공 기사", emoji: "🛡️" },
      { name: "바람 정령", emoji: "🌬️" },
      { name: "구름 양", emoji: "☁️" },
      { name: "천마", emoji: "🦄" },
      { name: "빛의 정령", emoji: "💡" },
      { name: "무지개 나비", emoji: "🦋" },
    ],
    boss: { name: "폭풍의 그리폰 왕", emoji: "🦅" },
    clearStory: "폭풍의 그리폰 왕이 하늘 저편으로 흩어지자, 구름 사이로 검게 갈라진 틈이 드러났다.",
  },
  {
    id: "rift",
    name: "균열의 심연",
    element: "어둠",
    monsters: [
      { name: "균열 촉수", emoji: "🐙" },
      { name: "그림자 처럼", emoji: "👤" },
      { name: "균열 눈동자", emoji: "👁️" },
      { name: "공허 조각", emoji: "🕳️" },
      { name: "균열 수호자", emoji: "⚔️" },
      { name: "심연 오징어", emoji: "🦑" },
      { name: "악몽 인형", emoji: "🪆" },
    ],
    boss: { name: "균열의 파수꾼", emoji: "👁️‍🗨️" },
    clearStory: "균열의 파수꾼을 물리쳤지만, 그 너머엔 아직 더 깊은 어둠이 남아있는 듯하다. (이야기는 계속됩니다)",
  },
  {
    id: "dragonNest",
    name: "용의 둥지",
    element: "불",
    monsters: [
      { name: "붉은 드레이크", emoji: "🐲" },
      { name: "화염 도마뱀", emoji: "🦎" },
      { name: "용의 하수인", emoji: "🗡️" },
      { name: "불꽃 박쥐", emoji: "🦇" },
      { name: "마그마 정령", emoji: "🌋" },
      { name: "용알 지킴이", emoji: "🥚" },
      { name: "그림자 이무기", emoji: "🐍" },
    ],
    boss: { name: "고대 홍룡", emoji: "🐉" },
    clearStory: "고대 홍룡이 둥지와 함께 무너지자, 바다 밑으로 가라앉은 유적의 빛이 수면 위로 새어 나왔다.",
  },
  {
    id: "sunkenRuins",
    name: "심해 유적",
    element: "물",
    monsters: [
      { name: "인어 전사", emoji: "🧜" },
      { name: "심해 아귀", emoji: "🐡" },
      { name: "해파리 정령", emoji: "🎐" },
      { name: "산호 골렘", emoji: "🪸" },
      { name: "유령 선원", emoji: "🏴‍☠️" },
      { name: "대왕 문어", emoji: "🐙" },
      { name: "진주 정령", emoji: "🦪" },
    ],
    boss: { name: "심해 크라켄", emoji: "🦑" },
    clearStory: "심해 크라켄이 가라앉자, 물 위로 비친 밤하늘에서 별빛이 쏟아지는 신전의 계단이 드러났다.",
  },
  {
    id: "starTemple",
    name: "별의 신전",
    element: "빛",
    monsters: [
      { name: "별빛 정령", emoji: "🌟" },
      { name: "타락한 사제", emoji: "🕯️" },
      { name: "유성 골렘", emoji: "☄️" },
      { name: "은하 나비", emoji: "🦋" },
      { name: "별지기 수호병", emoji: "🗿" },
      { name: "초신성 정령", emoji: "💫" },
      { name: "성좌뱀", emoji: "🐍" },
    ],
    boss: { name: "타락한 별의 수호자", emoji: "🌠" },
    clearStory: "타락한 별의 수호자를 봉인했다. 「새벽의 등불」 길드원들은 잠시 숨을 돌리며, 다음 이야기를 기다리기로 했다.",
  },
];
