// 지역 정보. 새 지역을 추가하려면 이 배열 끝에 항목을 하나 더 넣으면 된다.
export const regions = [
  {
    id: "forest",
    name: "초록 숲",
    element: "자연",
    monsters: [
      { name: "슬라임", emoji: "🟢" },
      { name: "고블린", emoji: "👺" },
      { name: "늑대", emoji: "🐺" },
      { name: "버섯괴물", emoji: "🍄" },
      { name: "멧돼지", emoji: "🐗" },
    ],
    boss: { name: "고블린 족장", emoji: "👹" },
    clearStory: "고블린 족장을 쓰러뜨리자, 숲 너머로 향하는 낡은 갱도 입구가 드러났다.",
  },
  {
    id: "mine",
    name: "버려진 광산",
    element: "어둠",
    monsters: [
      { name: "박쥐", emoji: "🦇" },
      { name: "스켈레톤", emoji: "💀" },
      { name: "두더지 광부", emoji: "⛏️" },
      { name: "동굴 거미", emoji: "🕷️" },
      { name: "좀비 광부", emoji: "🧟" },
    ],
    boss: { name: "해골 광산왕", emoji: "☠️" },
    clearStory: "해골 광산왕이 무너지며, 안개 자욱한 늪으로 이어지는 길이 열렸다.",
  },
  {
    id: "swamp",
    name: "안개 늪지",
    element: "물",
    monsters: [
      { name: "도마뱀 전사", emoji: "🦎" },
      { name: "늪 마녀", emoji: "🧙‍♀️" },
      { name: "거대 개구리", emoji: "🐸" },
      { name: "악어", emoji: "🐊" },
      { name: "늪 지네", emoji: "🐛" },
    ],
    boss: { name: "늪의 마녀 모르가", emoji: "🧙" },
    clearStory: "늪의 마녀 모르가를 물리쳤다. 다음 이야기는 계속됩니다...",
  },
  {
    id: "canyon",
    name: "불꽃 협곡",
    element: "불",
    monsters: [
      { name: "화염 정령", emoji: "🔥" },
      { name: "오우거", emoji: "👹" },
      { name: "용암 거북", emoji: "🐢" },
      { name: "마그마 웜", emoji: "🪱" },
      { name: "불꽃 임프", emoji: "😈" },
    ],
    boss: { name: "화산 거인", emoji: "🌋" },
    clearStory: "화산 거인이 무너지자 협곡의 열기가 가라앉고, 저 멀리 얼어붙은 성채가 보이기 시작했다.",
  },
  {
    id: "citadel",
    name: "얼음 성채",
    element: "물",
    monsters: [
      { name: "서리 기사", emoji: "🥶" },
      { name: "설인", emoji: "⛄" },
      { name: "아이스 골렘", emoji: "🧊" },
      { name: "펭귄 전사", emoji: "🐧" },
      { name: "눈보라 정령", emoji: "❄️" },
    ],
    boss: { name: "아이스 드래곤", emoji: "🐉" },
    clearStory: "아이스 드래곤을 쓰러뜨렸다. 성채 너머 하늘에 떠 있는 섬이 어렴풋이 보인다.",
  },
];
